#pragma once
#include "esphome/core/component.h"
#include "esphome/components/sensor/sensor.h"
#include "esp_sleep.h"
#include "ulp_lp_core.h"

// Auto-generated by IDF ULP build from your ulp/main.c variable names
// ulp_ prefix is added automatically
extern uint32_t ulp_sum;
extern uint32_t ulp_max_value;

// Auto-generated binary symbols
extern const uint8_t ulp_anemometer_ulp_bin_start[]
    asm("_binary_ulp_anemometer_ulp_bin_start");
extern const uint8_t ulp_anemometer_ulp_bin_end[]
    asm("_binary_ulp_anemometer_ulp_bin_end");

namespace esphome {
namespace anemometer_ulp {

class AnemometerULPComponent : public PollingComponent {
 public:
  void set_sum_sensor(sensor::Sensor *s)   { sum_sensor_ = s; }
  void set_max_sensor(sensor::Sensor *s)   { max_sensor_ = s; }
  void set_speed_factor(float f)           { speed_factor_ = f; }

  void setup() override {
    if (esp_sleep_get_wakeup_cause() != ESP_SLEEP_WAKEUP_TIMER) {
      ESP_LOGI("anemometer_ulp", "First boot — loading ULP");
      load_ulp_();
    } else {
      ESP_LOGI("anemometer_ulp", "Timer wakeup — reading counters");
    }
  }

  void update() override {
    uint32_t raw_sum = ulp_sum;
    uint32_t raw_max = ulp_max_value;

    if (sum_sensor_) sum_sensor_->publish_state(raw_sum / 120.0f * speed_factor_);
    if (max_sensor_) max_sensor_->publish_state(raw_max * speed_factor_);
  }

 private:
  sensor::Sensor *sum_sensor_{nullptr};
  sensor::Sensor *max_sensor_{nullptr};
  float speed_factor_{1.0f};

  void load_ulp_() {
    ESP_ERROR_CHECK(ulp_lp_core_load_binary(
        ulp_anemometer_ulp_bin_start,
        ulp_anemometer_ulp_bin_end - ulp_anemometer_ulp_bin_start
    ));
    ulp_lp_core_cfg_t cfg = {
        .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER,
        .lp_timer_sleep_duration_us = 10000,  // 10ms = matches your SAMPLE_TICKS
    };
    ESP_ERROR_CHECK(ulp_lp_core_run(&cfg));
  }
};

}  // namespace anemometer_ulp
}  // namespace esphome
